"""Built-in reference data for popular houseplants.

Populate SPECIES with one dict per plant, shaped like:

    {
        "name": "Snake Plant",
        "scientific_name": "Dracaena trifasciata",
        "watering_frequency_days": 14,
        "sunlight_needs": "Low light",
        "description": "Very drought-tolerant; let soil dry out completely between waterings.",
        "long_description": "A fuller paragraph shown when the user expands 'more details'.",
        "source_name": "NC State Extension Plant Toolbox",
        "source_url": "https://plants.ces.ncsu.edu/plants/dracaena-trifasciata/",
    }

`scientific_name` and `long_description` are optional (pass None if you
don't have one). `seed_species(db, SpeciesGuide)` upserts this list into
the database by `name` (case-sensitive match) - safe to call every time
the app starts. Editing an entry here and restarting the app updates the
stored row; it does not touch any plant a user has already saved with
those values.
"""

SPECIES = [
    {
        "name": 'Pothos',
        "scientific_name": 'Epipremnum aureum',
        "watering_frequency_days": 9,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Trailing vine that tolerates low light and forgives missed waterings.',
        "long_description": 'One of the most forgiving houseplants around. It grows in low to bright indirect light, though variegated leaves color up best with more light. Let the top inch or two of soil dry before watering again, and trim leggy vines to keep it full.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/epipremnum-aureum/',
    },
    {
        "name": 'Snake Plant',
        "scientific_name": 'Dracaena trifasciata',
        "watering_frequency_days": 21,
        "sunlight_needs": 'Low light',
        "description": 'Stores water in thick leaves; overwatering is the main risk.',
        "long_description": 'Snake plants tolerate deep shade and irregular watering better than almost any other houseplant. Let the soil dry out completely between waterings — root rot from overwatering is far more common than any problem from underwatering.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/dracaena-trifasciata/',
    },
    {
        "name": 'ZZ Plant',
        "scientific_name": 'Zamioculcas zamiifolia',
        "watering_frequency_days": 18,
        "sunlight_needs": 'Low light',
        "description": 'Rhizomes store water; thrives even in dim rooms.',
        "long_description": "ZZ plant's underground rhizomes let it go weeks without water. It tolerates low light well, though it grows faster in medium to bright indirect light. Water only once the soil is fully dry, and cut back further in winter.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/zamioculcas-zamiifolia/',
    },
    {
        "name": 'Monstera',
        "scientific_name": 'Monstera deliciosa',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Fast grower that wants bright indirect light and steady moisture.',
        "long_description": 'Monstera deliciosa develops its signature split leaves fastest in bright, indirect light with consistently moist (not soggy) soil. Water when the top couple inches of soil are dry, and give it something to climb as it matures.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/monstera-deliciosa/',
    },
    {
        "name": 'Peace Lily',
        "scientific_name": 'Spathiphyllum',
        "watering_frequency_days": 6,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Droops visibly when thirsty, making it easy to read.',
        "long_description": 'Peace lilies prefer partial to deep shade — never direct sun — and evenly moist soil. Leaves droop noticeably when the plant wants water and perk back up within hours of watering, a handy built-in indicator.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/spathiphyllum/',
    },
    {
        "name": 'Spider Plant',
        "scientific_name": 'Chlorophytum comosum',
        "watering_frequency_days": 8,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Adaptable arching foliage that produces trailing baby plantlets.',
        "long_description": 'Spider plants tolerate a wide range of light from medium to fairly deep shade but dislike direct sun. Keep soil lightly moist, reduce watering in winter, and use filtered or distilled water if tap water causes brown leaf tips.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/chlorophytum-comosum/',
    },
    {
        "name": 'Rubber Plant',
        "scientific_name": 'Ficus elastica',
        "watering_frequency_days": 10,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Glossy, stiff leaves on a plant that dislikes being moved.',
        "long_description": 'Rubber plants want bright indirect light and dislike cold drafts or frequent relocation. Water when the top couple inches of soil dry out, and wipe the broad leaves occasionally so they can photosynthesize efficiently.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/ficus-elastica/',
    },
    {
        "name": 'Fiddle Leaf Fig',
        "scientific_name": 'Ficus lyrata',
        "watering_frequency_days": 8,
        "sunlight_needs": 'Bright, indirect light',
        "description": "Statement tree that's picky about light consistency and overwatering.",
        "long_description": 'Fiddle leaf figs want bright indirect light and hate being moved or overwatered. Let the top couple inches of soil dry before watering again, and keep it away from cold drafts and heating vents — sudden changes cause leaf drop.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/ficus-lyrata/',
    },
    {
        "name": 'Aloe Vera',
        "scientific_name": 'Aloe vera',
        "watering_frequency_days": 14,
        "sunlight_needs": 'Direct sunlight',
        "description": 'Succulent that wants full sun and to dry out completely between waterings.',
        "long_description": 'Aloe vera thrives in full sun to partial shade and very well-drained, succulent-mix soil. Let it dry out completely before watering again, and water even less in winter — overwatering is the most common way to lose this plant.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/aloe-vera/',
    },
    {
        "name": 'Chinese Evergreen',
        "scientific_name": 'Aglaonema',
        "watering_frequency_days": 9,
        "sunlight_needs": 'Low light',
        "description": 'Patterned foliage that tolerates low light better than most.',
        "long_description": 'Chinese evergreen handles low to medium light well, though more heavily variegated cultivars want a bit more brightness to keep their patterning. Let the top inch of soil dry between waterings and keep it away from cold drafts.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/aglaonema/',
    },
    {
        "name": 'Heartleaf Philodendron',
        "scientific_name": 'Philodendron hederaceum',
        "watering_frequency_days": 8,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Easygoing trailing vine with glossy heart-shaped leaves.',
        "long_description": 'Heartleaf philodendron tolerates medium to low light and is one of the most forgiving trailing houseplants. Water when the top inch or two of soil is dry, and trim vines back periodically to keep it bushy rather than sparse.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/philodendron-hederaceum/',
    },
    {
        "name": 'English Ivy',
        "scientific_name": 'Hedera helix',
        "watering_frequency_days": 6,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Classic trailing vine that likes cooler rooms and steady moisture.',
        "long_description": 'English ivy prefers medium to bright indirect light and cooler indoor temperatures. Keep soil lightly moist but not soggy, and mist occasionally — dry indoor air can invite spider mites.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/hedera-helix/',
    },
    {
        "name": 'Boston Fern',
        "scientific_name": 'Nephrolepis exaltata',
        "watering_frequency_days": 4,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Lush fronds that want consistently moist soil and high humidity.',
        "long_description": "Boston fern prefers medium, indirect light and soil that stays evenly moist — it doesn't like to fully dry out. Boost humidity with a pebble tray or humidifier, especially in dry winter air, to prevent crispy frond tips.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/nephrolepis-exaltata/',
    },
    {
        "name": 'Dragon Tree',
        "scientific_name": 'Dracaena marginata',
        "watering_frequency_days": 12,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Slim, spiky leaves on a slow-growing, drought-tolerant trunk.',
        "long_description": "Dragon tree tolerates medium to bright indirect light and prefers to dry out somewhat between waterings. It's sensitive to fluoride in tap water, which can cause brown leaf tips, so filtered or rain water helps.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/dracaena-marginata/',
    },
    {
        "name": 'Croton',
        "scientific_name": 'Codiaeum variegatum',
        "watering_frequency_days": 5,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Bold, multicolored foliage that needs bright light to stay vivid.',
        "long_description": 'Croton needs bright light — including some direct morning sun — to keep its red, orange, and yellow leaf coloring. Keep soil consistently moist and provide high humidity; it will drop leaves if it dries out or sits in a cold draft.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/codiaeum-variegatum/',
    },
    {
        "name": 'Calathea',
        "scientific_name": 'Calathea orbifolia',
        "watering_frequency_days": 5,
        "sunlight_needs": 'Medium, indirect light',
        "description": "Patterned prayer-plant relative that's particular about humidity.",
        "long_description": 'Calathea wants medium, indirect light — direct sun fades its patterned leaves — and consistently moist soil. High humidity and distilled or filtered water help prevent the crispy brown edges this genus is known for.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/calathea-orbifolia/',
    },
    {
        "name": 'Jade Plant',
        "scientific_name": 'Crassula ovata',
        "watering_frequency_days": 14,
        "sunlight_needs": 'Direct sunlight',
        "description": 'Thick-leaved succulent tree that wants bright light and dry spells.',
        "long_description": 'Jade plant does best with several hours of direct or bright light a day and well-drained succulent soil. Let it dry out fully between waterings — it stores water in its leaves and is far more likely to suffer from overwatering than drought.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/crassula-ovata/',
    },
    {
        "name": 'African Violet',
        "scientific_name": 'Saintpaulia ionantha',
        "watering_frequency_days": 6,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Fuzzy-leaved bloomer that dislikes water on its foliage.',
        "long_description": 'African violets want bright, indirect light — an east- or north-facing window works well — and evenly moist soil. Water from below or carefully at the soil line, since water sitting on the fuzzy leaves can cause spotting.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/saintpaulia-ionantha/',
    },
    {
        "name": 'Bird of Paradise',
        "scientific_name": 'Strelitzia reginae',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Large tropical leaves that want bright light to avoid tearing and legginess.',
        "long_description": 'Bird of paradise wants bright light, including some direct sun, to grow sturdy, unblemished leaves. Keep soil evenly moist during the growing season and let it dry slightly between waterings in winter.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/strelitzia-reginae/',
    },
    {
        "name": 'Areca Palm',
        "scientific_name": 'Dypsis lutescens',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Feathery fronds that want bright light and consistent moisture.',
        "long_description": "Areca palm prefers bright indirect light and evenly moist, well-draining soil — it doesn't like to fully dry out or sit in standing water. Brown frond tips are usually a sign of low humidity or mineral buildup from tap water.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/dypsis-lutescens/',
    },
    {
        "name": 'Parlor Palm',
        "scientific_name": 'Chamaedorea elegans',
        "watering_frequency_days": 9,
        "sunlight_needs": 'Low light',
        "description": "Compact, shade-tolerant palm that's easy to overwater.",
        "long_description": "Parlor palm is one of the most shade-tolerant palms and does fine in low to medium light. Let the top inch or two of soil dry between waterings — it's more sensitive to soggy soil and root rot than to missed waterings.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/chamaedorea-elegans/',
    },
    {
        "name": 'Bromeliad',
        "scientific_name": 'Guzmania lingulata',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Medium, indirect light',
        "description": "Rosette-shaped epiphyte that's watered in its central cup, not the soil.",
        "long_description": "Bromeliads prefer medium, indirect light and are traditionally watered by keeping their central rosette 'cup' filled, flushing and refilling it weekly, with just light moisture in the potting mix itself.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/guzmania-lingulata/',
    },
    {
        "name": 'Christmas Cactus',
        "scientific_name": 'Schlumbergera',
        "watering_frequency_days": 10,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Segmented, leafless stems that bloom with shorter days and cooler nights.',
        "long_description": "Unlike desert cacti, Christmas cactus is a tropical epiphyte that prefers bright indirect light and soil that's kept lightly moist rather than bone-dry. Let the top inch dry between waterings, and reduce watering slightly after blooming.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/schlumbergera/',
    },
    {
        "name": 'Orchid (Phalaenopsis)',
        "scientific_name": 'Phalaenopsis',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Epiphytic bloomer grown in bark, watered on a weekly cycle.',
        "long_description": 'Phalaenopsis orchids grow in bark or moss rather than potting soil and want medium, indirect light. Water thoroughly about once a week, letting the roots dry out somewhat between waterings, and avoid letting water sit in the crown.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/phalaenopsis/',
    },
    {
        "name": 'Ponytail Palm',
        "scientific_name": 'Beaucarnea recurvata',
        "watering_frequency_days": 18,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Bulbous water-storing trunk topped with curling, grass-like leaves.',
        "long_description": 'Despite its name, ponytail palm is a succulent, not a true palm, and stores water in its swollen base. It wants bright light and should dry out completely between the infrequent waterings it needs.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/beaucarnea-recurvata/',
    },
    {
        "name": 'String of Pearls',
        "scientific_name": 'Curio rowleyanus',
        "watering_frequency_days": 10,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Trailing succulent with bead-like leaves that store water.',
        "long_description": "String of pearls wants bright light, including some gentle direct sun, and soil that dries out fully between waterings. Its round, pea-like leaves store water, so overwatering — not underwatering — is the main way it's lost.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/curio-rowleyanus/',
    },
    {
        "name": 'Prayer Plant',
        "scientific_name": 'Maranta leuconeura',
        "watering_frequency_days": 5,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Patterned leaves that fold up at night like hands in prayer.',
        "long_description": 'Prayer plant likes medium, indirect light — direct sun scorches the leaf pattern — and consistently moist soil. High humidity and filtered water help avoid the brown leaf edges this plant is prone to in dry indoor air.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/maranta-leuconeura/',
    },
    {
        "name": 'Chinese Money Plant',
        "scientific_name": 'Pilea peperomioides',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Round, coin-shaped leaves on a plant that produces easy-to-share offsets.',
        "long_description": 'Pilea peperomioides wants bright indirect light — rotate it regularly since it leans hard toward light sources — and to dry out slightly between waterings. It readily produces baby plantlets at its base that can be potted up separately.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/pilea-peperomioides/',
    },
    {
        "name": 'Anthurium',
        "scientific_name": 'Anthurium andraeanum',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Glossy, heart-shaped blooms that last for weeks at a time.',
        "long_description": 'Anthurium prefers medium to bright indirect light and evenly moist, well-draining soil. Its long-lasting waxy flowers (actually a modified leaf called a spathe) appear more reliably with consistent warmth and humidity.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/anthurium-andraeanum/',
    },
    {
        "name": 'Cast Iron Plant',
        "scientific_name": 'Aspidistra elatior',
        "watering_frequency_days": 10,
        "sunlight_needs": 'Low light',
        "description": 'Nearly indestructible, dark green foliage built for neglect.',
        "long_description": 'Cast iron plant earns its name — it tolerates low light, irregular watering, and general neglect better than almost any other houseplant. Let the soil dry out somewhat between waterings and avoid direct sun, which can scorch the leaves.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/aspidistra-elatior/',
    },
    {
        "name": 'Air Plant',
        "scientific_name": 'Tillandsia',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Soil-free epiphyte that absorbs water through its leaves.',
        "long_description": 'Air plants grow without soil and want bright, indirect light. Rather than a soil watering schedule, mist several times a week or soak fully in water for 20-30 minutes weekly, then shake off excess water so the base can dry out.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/tillandsia/',
    },
    {
        "name": 'Bamboo Palm',
        "scientific_name": 'Chamaedorea seifrizii',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Low light',
        "description": 'Clustering, cane-like palm that tolerates dim rooms well.',
        "long_description": 'Bamboo palm tolerates low to medium light better than most palms and prefers soil kept lightly, evenly moist. Avoid letting it sit in standing water, and boost humidity if leaf tips start browning.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/chamaedorea-seifrizii/',
    },
    {
        "name": 'Weeping Fig',
        "scientific_name": 'Ficus benjamina',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Classic indoor tree that drops leaves when its conditions change.',
        "long_description": 'Weeping fig wants bright, indirect light and is notorious for dropping leaves after a move or change in light. Keep its location and watering routine consistent — water when the top inch or two of soil is dry.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/ficus-benjamina/',
    },
    {
        "name": 'Alocasia',
        "scientific_name": 'Alocasia amazonica',
        "watering_frequency_days": 6,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Dramatic arrow-shaped leaves with striking pale veining.',
        "long_description": "Alocasia wants bright, indirect light and consistently moist (never soggy) soil, plus higher humidity than most homes offer naturally. It's more finicky than many houseplants and often goes dormant, dropping leaves, in low light or winter.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/alocasia/',
    },
    {
        "name": 'Hoya (Wax Plant)',
        "scientific_name": 'Hoya carnosa',
        "watering_frequency_days": 10,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Thick, waxy leaves on a slow-growing vine that blooms with age.',
        "long_description": "Hoya prefers bright, indirect light — some direct morning sun helps it bloom — and semi-succulent care: let the top couple inches of soil dry before watering again. It's a slow grower that rewards patience with fragrant, star-shaped flower clusters.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/hoya-carnosa/',
    },
    {
        "name": 'Peperomia',
        "scientific_name": 'Peperomia obtusifolia',
        "watering_frequency_days": 9,
        "sunlight_needs": 'Medium, indirect light',
        "description": "Compact, thick-leaved plant that's easy to overwater.",
        "long_description": 'Peperomia obtusifolia does well in medium, indirect light and semi-succulent care — let the top half of the soil dry before watering again. Its thick leaves store some moisture, so it tolerates missed waterings better than soggy soil.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/peperomia-obtusifolia/',
    },
    {
        "name": 'Ficus Audrey',
        "scientific_name": 'Ficus benghalensis',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Fuzzy-leaved fig tree, a hardier alternative to fiddle leaf fig.',
        "long_description": 'Ficus Audrey wants bright, indirect light and is somewhat more tolerant of care lapses than its relative the fiddle leaf fig. Water when the top couple inches of soil are dry and keep it away from cold drafts.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/ficus-benghalensis/',
    },
    {
        "name": 'Rex Begonia',
        "scientific_name": 'Begonia rex',
        "watering_frequency_days": 6,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Ornamental foliage plant with swirling, iridescent leaf patterns.',
        "long_description": 'Rex begonia wants medium, indirect light and evenly moist soil, but is prone to rot if overwatered or misted directly on the leaves. Water at the soil line and provide good air circulation to prevent powdery mildew.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/begonia/',
    },
    {
        "name": 'String of Hearts',
        "scientific_name": 'Ceropegia woodii',
        "watering_frequency_days": 12,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Delicate trailing vine with heart-shaped, marbled leaves.',
        "long_description": 'String of hearts is a semi-succulent vine that wants bright, indirect light — some gentle direct sun encourages compact growth and better leaf coloring. Let the soil dry out fully between waterings; it stores water in its leaves and small tubers.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/ceropegia-woodii/',
    },
    {
        "name": 'Kalanchoe',
        "scientific_name": 'Kalanchoe blossfeldiana',
        "watering_frequency_days": 10,
        "sunlight_needs": 'Direct sunlight',
        "description": 'Succulent bloomer with clusters of long-lasting flowers.',
        "long_description": "Kalanchoe wants bright light, including several hours of direct sun, to keep blooming well. Let the soil dry out between waterings — it's a succulent and is much more tolerant of drought than of consistently wet soil.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/kalanchoe-blossfeldiana/',
    },
    {
        "name": 'Dumb Cane',
        "scientific_name": 'Dieffenbachia seguine',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Broad, patterned leaves on an easy-care tropical staple.',
        "long_description": "Dieffenbachia grows well in medium, indirect light and wants soil kept lightly moist, drying slightly at the surface between waterings. Its sap is irritating if chewed, which is where the 'dumb cane' name comes from — keep it away from curious pets and kids.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/dieffenbachia-seguine/',
    },
    {
        "name": 'Swiss Cheese Vine',
        "scientific_name": 'Monstera adansonii',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Smaller, faster-growing cousin of Monstera deliciosa with oval holes.',
        "long_description": 'Monstera adansonii wants bright, indirect light and warm, humid conditions; direct sun can scorch its leaves. Water when the top inch or two of soil is dry, and give it a moss pole or trellis to climb for the largest, most fenestrated leaves.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/monstera-adansonii/',
    },
    {
        "name": 'Majesty Palm',
        "scientific_name": 'Ravenea rivularis',
        "watering_frequency_days": 5,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Large, arching fronds that need steady moisture and humidity.',
        "long_description": "Majesty palm wants bright, indirect light and consistently moist soil — unlike many palms, it doesn't like to dry out between waterings. Low humidity and inconsistent watering are the most common causes of browning fronds.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/ravenea-rivularis/',
    },
    {
        "name": 'Corn Plant',
        "scientific_name": 'Dracaena fragrans',
        "watering_frequency_days": 10,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Cornstalk-like cane topped with arching, strappy leaves.',
        "long_description": "Corn plant tolerates medium to fairly low light and prefers to dry out somewhat between waterings. Like other dracaenas, it's sensitive to fluoride and chlorine in tap water, which can cause brown leaf tips over time.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/dracaena-fragrans/',
    },
    {
        "name": 'Norfolk Island Pine',
        "scientific_name": 'Araucaria heterophylla',
        "watering_frequency_days": 6,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Soft-needled evergreen often sold as a living holiday tree.',
        "long_description": 'Norfolk Island pine wants bright, indirect light — insufficient light causes sparse, leggy growth — and soil kept lightly moist. Avoid letting it dry out completely, and keep it away from heating vents that dry the air.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/araucaria-heterophylla/',
    },
    {
        "name": 'Lucky Bamboo',
        "scientific_name": 'Dracaena sanderiana',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Not a true bamboo — stalks are often grown rooted in water.',
        "long_description": "Lucky bamboo grows well in medium, indirect light and is commonly kept rooted in water rather than soil; change the water weekly if grown this way. Direct sun can scorch its leaves, and it's sensitive to chlorine and fluoride, so filtered water is best.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/dracaena-sanderiana/',
    },
    {
        "name": 'Money Tree',
        "scientific_name": 'Pachira aquatica',
        "watering_frequency_days": 10,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Braided-trunk tree often kept as a compact tabletop plant.',
        "long_description": "Money tree wants bright, indirect light and prefers to dry out somewhat between thorough waterings. It's commonly sold with braided trunks and is fairly tolerant of average indoor humidity, though it dislikes soggy soil.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/pachira-aquatica/',
    },
    {
        "name": 'Staghorn Fern',
        "scientific_name": 'Platycerium bifurcatum',
        "watering_frequency_days": 7,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Epiphytic fern often mounted on a board rather than potted.',
        "long_description": 'Staghorn fern is typically mounted on wood rather than grown in a pot, and prefers medium, indirect light. Water by soaking or thoroughly misting the root mass weekly, letting it dry somewhat between waterings to avoid rot.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/platycerium-bifurcatum/',
    },
    {
        "name": 'Watermelon Peperomia',
        "scientific_name": 'Peperomia argyreia',
        "watering_frequency_days": 9,
        "sunlight_needs": 'Medium, indirect light',
        "description": 'Compact plant with striped leaves resembling watermelon rind.',
        "long_description": 'Watermelon peperomia grows well in medium, indirect light and semi-succulent care — let the top half of the soil dry before watering again. Its thick, patterned leaves are prone to rot if kept too wet.',
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/peperomia-argyreia/',
    },
    {
        "name": "Burro's Tail",
        "scientific_name": 'Sedum morganianum',
        "watering_frequency_days": 14,
        "sunlight_needs": 'Bright, indirect light',
        "description": 'Trailing succulent with plump, bead-like leaves that bruise easily.',
        "long_description": "Burro's tail wants bright light, including some direct sun, and soil that dries out completely between waterings. Its fleshy leaves detach easily when handled, so it's best kept somewhere it won't be brushed against often.",
        "source_name": 'NC State Extension Plant Toolbox',
        "source_url": 'https://plants.ces.ncsu.edu/plants/sedum-morganianum/',
    },
]

_FIELDS = (
    "scientific_name",
    "watering_frequency_days",
    "sunlight_needs",
    "description",
    "long_description",
    "source_name",
    "source_url",
)


def seed_species(db, SpeciesGuide):
    if not SPECIES:
        return

    existing = {s.name: s for s in SpeciesGuide.query.all()}

    for entry in SPECIES:
        row = existing.get(entry["name"])
        if row is None:
            db.session.add(SpeciesGuide(**entry))
        else:
            for field in _FIELDS:
                if field in entry:
                    setattr(row, field, entry[field])

    db.session.commit()
